
name: 'dissertation_mmm'
version: '1.0.0'
config-version: 2

profile: 'dissertation_mmm'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  dissertation_mmm:
    staging:
      +materialized: view
    marts:
      +materialized: table
